language: ruby
sudo: false
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rspec"
gemfile:
  - gemfiles/virtus-0_5_x.gemfile
  - gemfiles/virtus-latest.gemfile
  - gemfiles/virtus-edge.gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - jruby-19mode
  - jruby-head
notifications:
  email:
    - manzan@gmail.com
addons:
  code_climate:
    repo_token: f8618d1de7dabe41776f844065242c2d7ade1d5c95ff3498886b4640a6bbaa01
